Replace termion with crossterm
cantino/mcfly pull request #296
Opened 2022-11-07 16:36 UTC by jtschuster

This isolates the changes from https://github.com/cantino/mcfly/pull/280 that are related to crossterm.

@cantino Hopefully this makes it easier to review and test yourself, and PowerShell/Windows support can be added separately.

2022-11-27 22:40 UTC, cantino commented
Is this ready for testing @jtschuster?

2022-11-30 20:35 UTC, jtschuster commented
@cantino Sorry for the delay, it should be ready to look at now.

2022-12-11 03:13 UTC, cantino requested changes
I get 

```
 $ thread 'main' panicked at 'McFly error: failed to read input IoError(Custom { kind: Other, error: "Failed to initialize input reader" })', src/interface.rs:413:43
 git st                                             note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                                                                                           2h 11m
```

On my Mac when I run this.

2022-12-12 00:19 UTC, jtschuster commented on src/interface.rs
> +                code: KeyCode::Enter,
I thought Enter would cover both, but I'll add \r and \n to be safe.

2022-12-12 06:57 UTC, jtschuster commented
It looks like there is a known issue with crossterm on mac when /dev/tty is used instead of stdin. Since it looks like zsh's zle uses the tty, that seems to be causing issues. It's working for me on linux with bash and zsh, and mac with bash, but not zsh.
There's a couple PR's looking to address the issue, one stale and one new:
https://github.com/crossterm-rs/crossterm/pull/407
https://github.com/crossterm-rs/crossterm/pull/711

2023-02-26 03:46 UTC, jtschuster commented
@cantino Sorry for letting this get stale, but it should be ready to take another look at now. The crashing on zsh issue was fixed in crossterm v0.26, and it seems to be working for me. Please take a look when you can.

2023-02-26 18:15 UTC, cantino commented
Thank you for your hard work on this @jtschuster. Have you been using this personally without issue?

2023-02-27 00:28 UTC, jtschuster commented
> Thank you for your hard work on this @jtschuster. Have you been using this personally without issue?

I use windows primarily, but I've been using https://github.com/cantino/mcfly/pull/280 without issues so far, and haven't hit issues testing this branch yet.

> Minor: The highlight color is a bit hard to read on my Mac on iTerm2:

I just pushed a commit that changes the highlight color to DarkGreen and it's much more readable.

> Is now a good time to allow color customization?

I wouldn't want to add too much to this PR, but it should be easy to rebase https://github.com/cantino/mcfly/pull/156 once this is in.

2023-02-27 00:42 UTC, cantino commented
In light mode, the text you've typed isn't visible when selected:

![image](https://user-images.githubusercontent.com/83835/221447776-d7af6d5c-e186-44ed-a2a2-fcf0caa48a2b.png)

While it is visible in dark mode:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/83835/221447793-fe873347-9212-4bf8-a59f-7839af1b9110.png">

And it is on master:
![image](https://user-images.githubusercontent.com/83835/221447935-448b55a5-225c-4ea4-9c33-27fc04624c64.png)

2023-02-27 01:14 UTC, jtschuster commented
Good catch! I've pushed a commit that makes it match the behavior in master.

2023-02-28 23:24 UTC, praveenperera commented
Thanks for the or @jtschuster, i’m going to test this out locally tomorrow. For now would you find fixing the last clippy warnings?

2023-03-03 17:24 UTC, praveenperera commented
@jtschuster @cantino I've been using this branch, its been good

2023-03-04 03:27 UTC, cantino commented
One more merge and I think we're good to go on this.

2023-03-04 19:56 UTC, cantino approved these changes

2023-03-04 19:56 UTC, merged

2023-03-04 19:56 UTC, cantino commented
Thanks @jtschuster! Awesome work.

2023-03-07 04:54 UTC, cantino commented
Released in v0.8.0.